name: 04 - Using Actions
on:
    push:
            
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folder
              run: ls  
        # 0. checkout the code from repo
        # 1. install deps of react app
        # 2. auto test

