name: 07 - Using Expressions
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
              type: boolean
              default: false
            
            
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print start-up data"
              if: ${{ inputs.debug == true}}
              run: |
                "Triggered by: ${{ github.event_name }}"
                "Branch: ${{ github.ref }}"
                "Commit SHA: ${{ github.sha }}"
                "Runner OS: ${{runner.os}}"
            - name: "[debug] Print when triggered from main"
              if: ${{ inputs.debug == true && github.ref == 'refs/head/master' }}
              run: echo "I was triggered from main"
            - name: Greeting
              run: echo "Hello, world"
              


