name: 09 - Using Functions
on:
    workflow_dispatch: 

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: echo "${{ github.event_name }}"
            - name: Print PR labels
              run: | 
                cat << EOF
                ${{ toJSON(github.event.pull_request.labels) }}
                EOF
            - name: Bug step
              if: failure() && contains(github.event.pull_request.title, 'fix')
              run: ""

            - name: Sleep for 20 seconds
              run: sleep 20
            - name: Failing step
              run: exit 1
            - name: Skippe step
              if: ${{ success() }}
              run: echo 'I will print if previous steps succeed'
            - name: Exec step
              if: ${{ failure() }}
              run: echo 'I will print if any previous step fails.'
            - name: Exec step
              if: ${{ !cancelled() }}
              run: echo 'I will always print, except when the workflow is cancelled'
            - name: Cancel step
              if: ${{ cancelled() }}
              run: echo 'I will always print, when the workflow is cancelled'

              