name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
              type: boolean
              default: false
              description: Skip deployment and only print build output
            target:
                type: ENVIRONMENT
                required: true
                description: Which environment the workflow will target"
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                    - v4
                default: v3
                description: Release from which to build and deploy"
            language: 
                type: string
                required: true
                default: python,javascript,go



jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            language: ${steps.vars.outputs.language_list}
        steps:
            - name: Build
              run: |
                echo "Building from tag ${{ inputs.tag }}"

            - name: Print GITHUB_OUTPUT path
              run: |
                echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"

            - name: Create an array of projects
              id: vars
              run: echo "::set-output name=language_list::$(jq 'split(",")' -Rc <(echo '${{ inputs.language }}'))"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: ${{ inputs.target }}
        steps:
            - name: Build
              if: ${{ inputs.dry-run == false }}
              run: |
                echo "Deploying to ${{ inputs.target }}"