name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      projects:
        required: true
        type: string # like project1,project2,project3
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.vars.outputs.project_list }}
      #output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Create an array of projects
        id: vars
        #run: echo "::set-output name=project_list::$(jq 'split(",")' -Rc <(echo '${{ inputs.projects }}'))"
        run: echo "project_list=hello" >> "$GITHUB_OUTPUT"
  
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - env:
          OUTPUT1: ${{needs.setup.outputs.output1}}
        run: echo "$OUTPUT1 $OUTPUT2"
  # :
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #       project: ${{ fromJson(needs.setup.outputs.projects) }}
  #   steps:
  #   - name: build project ${{ matrix.project }}
  #     run: echo "project=${{ matrix.project }}" 