name: 12 - Working with Outputs
on: 
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success
                    



jobs:
    build:
        runs-on: ubuntu-latest
        outputs: 
            build_status: ${{ steps.build.outputs.status}}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: |
                echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
            - name: Build
              run: echo "status=success" >> "$GITHUB_OUTPUT"
              id: build
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name : Deploy
              if : ${{ needs.build.outputs.build_status == 'success' }} 
              run: echo "Deploying.."
