name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
        use-cache:
            type: boolean
            description: Whether to execute cache step
        node-version:
            type: choice
            options:
              - 18.x
              - 20.x
              - 21.x
            default: 20.x
            description: Node description

jobs:
  install-deps :
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app/react-app
        outputs: 
            deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY}}
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Download cached dependencies
      id: cache
      if: ${{ inputs.use-cache }}
      uses: actions/cache@v3 
      with:
        path: react-app/react-app/node_modules
        key: deps-node-modules-${{ hashFiles('react-app/react-app/package-lock.json') }}

    - name: Install Dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: npm ci

    - name: Run unit test
      run: npm run test

    - name: Building
      run: npm run build

    - name: Deploying to nonprod
      run: |
        echo "Deploying to nonprod"
   
   
  build :
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: react-app/react-app

    needs: [install-deps]

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ inputs.node-version }}

        - name: Calculate cache_key
          id: cache-key
          run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('react-app/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"
        
        - name: Download cached dependencies
          id: cache
          if: ${{ inputs.use-cache }}
          uses: actions/cache@v3 
          with:
            path: react-app/react-app/node_modules
            key:  ${{ needs.install-deps.outputs.CACHE_KEY }}
      
        - name: Run unit test
          run: npm run test
      